export const IMAGES_RES = {
  wave_background: require('../../assets/images/bg_wave.png'),
  man_body: require('../../assets/images/man_body.png'),
  girl_body: require('../../assets/images/girl_body.png'),
  man_head: require('../../assets/images/man_head.png'),
  girl_head: require('../../assets/images/girl_head.png'),
  love_pic: require('../../assets/images/love-letter.png'),
  kirimTaaruf: require('../../assets/images/paper-plane.png'),
  terimaTaaruf: require('../../assets/images/complaint.png'),
  backIcon: require('../../assets/images/backIcon.png'),
  filter: require('../../assets/images/filter.png'),
  heart: require('../../assets/images/heart.png'),
  info: require('../../assets/images/idea.png'),
  gear: require('../../assets/images/gear.png'),
  premium: require('../../assets/images/premium.png'),
  sended: require('../../assets/images/sended.png'),
  logo: require('../../assets/images/logo.png'),
  grad: require('../../assets/images/grad.png'),
};
